nameOverride: svc-feed

replicaCount: 3

imagePullSecrets:
  - regcred

image:
  repository: registry.leultewolde.com/mereb/svc-feed
  env:
    - name: NODE_ENV
      value: production
    - name: SERVICE_NAME
      value: svc-feed
  envFrom:
    - configMapRef:
        name: svc-feed-prd-config
    - secretRef:
        name: svc-feed-prd-secrets
        optional: true

service:
  ports:
    - name: http
      port: 80
      targetPort: http
      containerPort: 4002

ingress:
  enabled: true
  className: kong
  annotations:
    kubernetes.io/ingress.class: kong
    cert-manager.io/cluster-issuer: letsencrypt-http
    konghq.com/strip-path: "true"
  hosts:
    - host: api.mereb.app
      paths:
        - path: /feed
          pathType: Prefix
          servicePort: http
  tls:
    - secretName: feed-prd-tls
      hosts:
        - api.mereb.app

configMap:
  enabled: true
  nameOverride: svc-feed-prd-config
  data:
    PORT: "4002"
    OIDC_ISSUER: https://idp.mereb.social/realms/mereb
    OIDC_AUDIENCE: mereb
    REDIS_URL: redis://platform-prd-redis-master.platform-prd.svc.cluster.local:6379/2
    KAFKA_BROKERS: platform-prd-redpanda-0.platform-prd-redpanda.platform-prd.svc.cluster.local:9092,platform-prd-redpanda-1.platform-prd-redpanda.platform-prd.svc.cluster.local:9092,platform-prd-redpanda-2.platform-prd-redpanda.platform-prd.svc.cluster.local:9092

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 640Mi
