replicaCount: 1

configMap:
  data:
    PORT: "4002"
    OIDC_AUDIENCE: account
    MEDIA_SERVICE_URL: http://svc-media-dev.apps-dev.svc.cluster.local
    MEDIA_CDN_ORIGIN: https://uploads-dev.mereb.app/media-dev
    REDIS_URL: redis://platform-dev-redis-master.platform-dev.svc.cluster.local:6379/2
    SPLUNK_HEC_URL: https://splunk-hec.mereb.app/services/collector/event
    SPLUNK_HEC_INDEX: logs-dev

resources:
  requests:
    cpu: 15m
    memory: 96Mi
  limits:
    cpu: 150m
    memory: 256Mi
