nameOverride: svc-feed

replicaCount: 1

imagePullSecrets:
  - regcred

image:
  repository: registry.leultewolde.com/mereb/svc-feed
  pullPolicy: Always
  env:
    - name: NODE_ENV
      value: production
    - name: SERVICE_NAME
      value: svc-feed
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://otel-collector-dev.platform-dev.svc.cluster.local:4318
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
    - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
      value: http/protobuf
    - name: OIDC_ISSUER
      valueFrom:
        configMapKeyRef:
          name: platform-identity-dev
          key: OIDC_ISSUER
  envFrom:
    - configMapRef:
        name: svc-feed-dev-config
    - secretRef:
        name: svc-feed-dev-secrets
        optional: true

service:
  ports:
    - name: http
      port: 80
      targetPort: http
      containerPort: 4002

ingress:
  enabled: true
  className: kong
  annotations:
    kubernetes.io/ingress.class: kong
    cert-manager.io/cluster-issuer: letsencrypt-http
    konghq.com/strip-path: "true"
  hosts:
    - host: api-dev.mereb.app
      paths:
        - path: /feed
          pathType: Prefix
          servicePort: http
  tls:
    - secretName: feed-dev-tls
      hosts:
        - api-dev.mereb.app

configMap:
  enabled: true
  nameOverride: svc-feed-dev-config
  data:
    PORT: "4002"
    OIDC_AUDIENCE: account
    MEDIA_SERVICE_URL: http://svc-media-dev.apps-dev.svc.cluster.local
    REDIS_URL: redis://platform-dev-redis-master.platform-dev.svc.cluster.local:6379/2
    KAFKA_BROKERS: platform-dev-redpanda-0.platform-dev-redpanda.platform-dev.svc.cluster.local:9092
    KAFKA_SSL: "true"
    KAFKA_SSL_INSECURE: "true"
    SPLUNK_HEC_URL: https://splunk-hec.mereb.app/services/collector/event
    SPLUNK_HEC_INDEX: logs-dev

resources:
  requests:
    cpu: 15m
    memory: 96Mi
  limits:
    cpu: 150m
    memory: 256Mi
